export const APP_ROUTES = {
  ROOT: '/',
  ID: '/:id',
  BLOGS: '/blogs',
  POSTS: '/posts',
  TESTING: '/testing',
  CLEAR_DATA: '/all-data',
  USERS: '/users',
  AUTH: '/auth',
  AUTH_LOGIN: '/login',
  AUTH_LOGOUT: '/logout',
  AUTH_REGISTRATION: '/registration',
  AUTH_REGISTRATION_CONFIRMATION: '/registration-confirmation',
  AUTH_REGISTRATION_EMAIL_RESENDING: '/registration-email-resending',
  AUTH_ME: '/me',
  AUTH_REFRESH_TOKEN: '/refresh-token',
  COMMENTS: '/comments',
} as const;
